const admin = require("firebase-admin");

// Initialisation Firebase Admin
const serviceAccount = require("./dev-serviceAccountKey.json");

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
});

const db = admin.firestore();

const fines = [
  {
    "id": "0bdCF5X4lCRdIuQxPxhY",
    "date": "2026-09-19",
    "comment": "",
    "playerId": "zjvnZVd7YUWGbeVHUj2uqYHLtcf2",
    "playerFirstName": "alexandre",
    "playerLastName": "couloir",
    "playerNickName": "alex",
    "matchDay": true,
    "ruleId": "EljtmnPY83UZXucSvkJe",
    "ruleLabel": "Retard < 5'",
    "amount": 4
  },
  {
    "id": "0xK3eqUB1tlybIcxBWiP",
    "date": "2026-09-13",
    "comment": "Contre",
    "playerId": "imPqpb4QodNbur8A2402Y0ViqtU2",
    "playerFirstName": "nathan",
    "playerLastName": "noumowe",
    "playerNickName": "noumox",
    "matchDay": true,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 8
  },
  {
    "id": "1ITFPQOBDYYENZWNx0nq",
    "date": "2026-09-25",
    "comment": "motion balek",
    "playerId": "T2u3qJAVmxaEQTtSR53ldAAQWDk2",
    "playerFirstName": "odelin",
    "playerLastName": "baubineau",
    "playerNickName": "o2",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "20pXrHkPDz8xWbazubQV",
    "date": "2026-09-11",
    "comment": "débile ",
    "playerId": "W6OaWBB73yYfVAZcMwapwKeGN3G3",
    "playerFirstName": "kévin",
    "playerLastName": "merit",
    "playerNickName": "kev",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "28jRmgnNu0shCZxms2Wf",
    "date": "2026-09-19",
    "comment": "Erreur de table",
    "playerId": "x1a3efMWZyUAnzjlhv73DK1ijxg2",
    "playerFirstName": "romain",
    "playerLastName": "lamirault",
    "playerNickName": "miro",
    "matchDay": true,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 8
  },
  {
    "id": "2el7zm2E6B3HWD3a3Wch",
    "date": "2026-09-25",
    "comment": "lobe la cage sans gardien",
    "playerId": "GHGR9vlmWHP1RUpFrykHyoWUao53",
    "playerFirstName": "gaspard",
    "playerLastName": "martin penard",
    "playerNickName": "gasp",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "2vXyhQxstW7mLurJn8Ed",
    "date": "2026-09-06",
    "comment": "",
    "playerId": "imPqpb4QodNbur8A2402Y0ViqtU2",
    "playerFirstName": "nathan",
    "playerLastName": "noumowe",
    "playerNickName": "noumox",
    "matchDay": false,
    "ruleId": "lVDcNgOuIHfmfljSx9Vd",
    "ruleLabel": "Oubli",
    "amount": 2
  },
  {
    "id": "2zMSR5RyFgxVJwIOlcHy",
    "date": "2026-09-13",
    "comment": "Racisme",
    "playerId": "imPqpb4QodNbur8A2402Y0ViqtU2",
    "playerFirstName": "nathan",
    "playerLastName": "noumowe",
    "playerNickName": "noumox",
    "matchDay": true,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 8
  },
  {
    "id": "3AepIIb8bvLAUqsnEV30",
    "date": "2026-09-11",
    "comment": "Balle sur le terrain",
    "playerId": "HF7TqiV8ajZ5dF3vTqqSdmZu4ht2",
    "playerFirstName": "estébane",
    "playerLastName": "gouhey",
    "playerNickName": "st",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "3rZ9zL9Ii3KurvcMU56h",
    "date": "2026-09-13",
    "comment": "Non boulard",
    "playerId": "RxCeoNlkiQTp3lzwRlqlN8FFAld2",
    "playerFirstName": "pierrick",
    "playerLastName": "royer",
    "playerNickName": "pierrick",
    "matchDay": true,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 8
  },
  {
    "id": "4LgTBF9iQ0iz3h87yW6W",
    "date": "2026-09-11",
    "comment": "débile",
    "playerId": "RxCeoNlkiQTp3lzwRlqlN8FFAld2",
    "playerFirstName": "pierrick",
    "playerLastName": "royer",
    "playerNickName": "pierrick",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "4dUCst7hsK5ShIH94PGV",
    "date": "2026-09-11",
    "comment": "débile",
    "playerId": "q1gmRkXPx0WIltpNhcovU0RI1X43",
    "playerFirstName": "arnaud",
    "playerLastName": "goacolou",
    "playerNickName": "nono",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "4w1Nc5tNYaAPQ6jg7xCi",
    "date": "2026-09-19",
    "comment": "",
    "playerId": "iWw4sZUo6lZLYlVJhsK3Jsjy0cH2",
    "playerFirstName": "julien",
    "playerLastName": "tessier",
    "playerNickName": "tess",
    "matchDay": true,
    "ruleId": "EljtmnPY83UZXucSvkJe",
    "ruleLabel": "Retard < 5'",
    "amount": 4
  },
  {
    "id": "54XrjiaA7fuv1eIhUfri",
    "date": "2026-09-20",
    "comment": "",
    "playerId": "r2VQWG7glterTCdxOWGdNfwHewm1",
    "playerFirstName": "basile",
    "playerLastName": "bolcato",
    "playerNickName": "baz",
    "matchDay": true,
    "ruleId": "3Avbmn5WDjhkbQvcsNTz",
    "ruleLabel": "Salissure",
    "amount": 4
  },
  {
    "id": "5NMQKJj949mAKK6w6xEH",
    "date": "2026-09-11",
    "comment": "débile",
    "playerId": "imPqpb4QodNbur8A2402Y0ViqtU2",
    "playerFirstName": "nathan",
    "playerLastName": "noumowe",
    "playerNickName": "noumox",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "5hehQhrFoHZHQmlpwouM",
    "date": "2026-09-25",
    "comment": "balle gogolisée",
    "playerId": "q1gmRkXPx0WIltpNhcovU0RI1X43",
    "playerFirstName": "arnaud",
    "playerLastName": "goacolou",
    "playerNickName": "nono",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "5vIHCTXRF9admEM8RYUu",
    "date": "2026-09-13",
    "comment": "",
    "playerId": "x1a3efMWZyUAnzjlhv73DK1ijxg2",
    "playerFirstName": "romain",
    "playerLastName": "lamirault",
    "playerNickName": "miro",
    "matchDay": true,
    "ruleId": "3Avbmn5WDjhkbQvcsNTz",
    "ruleLabel": "Salissure",
    "amount": 4
  },
  {
    "id": "79JaLytXjD1N4p5qGq2M",
    "date": "2026-09-13",
    "comment": "",
    "playerId": "iWw4sZUo6lZLYlVJhsK3Jsjy0cH2",
    "playerFirstName": "julien",
    "playerLastName": "tessier",
    "playerNickName": "tess",
    "matchDay": true,
    "ruleId": "AOgAsPJcNFg0To6yHtve",
    "ruleLabel": "Quéquette",
    "amount": 5
  },
  {
    "id": "7Yop0EpxW4oFms12JNh8",
    "date": "2026-09-11",
    "comment": "",
    "playerId": "r2VQWG7glterTCdxOWGdNfwHewm1",
    "playerFirstName": "basile",
    "playerLastName": "bolcato",
    "playerNickName": "baz",
    "matchDay": false,
    "ruleId": "3Avbmn5WDjhkbQvcsNTz",
    "ruleLabel": "Salissure",
    "amount": 2
  },
  {
    "id": "7lsDg6waB3Y79Skvr7kc",
    "date": "2026-09-02",
    "comment": "",
    "playerId": "TSY4IqLIqoWG6f6UhVOsXvyQmnc2",
    "playerFirstName": "baptiste",
    "playerLastName": "Baubineau",
    "playerNickName": "baptiste",
    "matchDay": false,
    "ruleId": "EljtmnPY83UZXucSvkJe",
    "ruleLabel": "Retard < 5'",
    "amount": 2
  },
  {
    "id": "7yTgCj3tGOPhyDPrmKmZ",
    "date": "2026-09-06",
    "comment": "Contestation (je suis sympa, normalement c'est 10 balles)",
    "playerId": "GHGR9vlmWHP1RUpFrykHyoWUao53",
    "playerFirstName": "gaspard",
    "playerLastName": "martin penard",
    "playerNickName": "gasp",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "8VhAdoNBvPyZ83D8dn72",
    "date": "2026-09-20",
    "comment": "Putain jsuis allé à point P",
    "playerId": "XN33ZCiXKsVWi6j34URzz7nlLYq2",
    "playerFirstName": "legault",
    "playerLastName": "anatole",
    "playerNickName": "anat",
    "matchDay": true,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 8
  },
  {
    "id": "9DPx5SxIXJAgK0FFYfO9",
    "date": "2026-09-11",
    "comment": "",
    "playerId": "DkxnMTfHHCXxECTwKQJx0UJt1FI3",
    "playerFirstName": "emile",
    "playerLastName": "miot",
    "playerNickName": "emile",
    "matchDay": false,
    "ruleId": "EljtmnPY83UZXucSvkJe",
    "ruleLabel": "Retard < 5'",
    "amount": 2
  },
  {
    "id": "9uuuINe3PPn6oEWud2pm",
    "date": "2026-09-02",
    "comment": "",
    "playerId": "jnHag6vVpYZGlRMEPek7a6sA1GD2",
    "playerFirstName": "anthony",
    "playerLastName": "haté",
    "playerNickName": "grantho",
    "matchDay": false,
    "ruleId": "EljtmnPY83UZXucSvkJe",
    "ruleLabel": "Retard < 5'",
    "amount": 2
  },
  {
    "id": "A6Jcg0n2vKtK5w6lNQMl",
    "date": "2026-09-20",
    "comment": "Donnée par boulif",
    "playerId": "GHGR9vlmWHP1RUpFrykHyoWUao53",
    "playerFirstName": "gaspard",
    "playerLastName": "martin penard",
    "playerNickName": "gasp",
    "matchDay": false,
    "ruleId": "nDe1tvnRY3O5a4qlb3CQ",
    "ruleLabel": "Homme du match",
    "amount": 2
  },
  {
    "id": "AUOgtEGTF0XGcS1QJ2w0",
    "date": "2026-09-19",
    "comment": "Motion 1",
    "playerId": "r2VQWG7glterTCdxOWGdNfwHewm1",
    "playerFirstName": "basile",
    "playerLastName": "bolcato",
    "playerNickName": "baz",
    "matchDay": true,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 8
  },
  {
    "id": "AY6lfHVYka3S8vX4IJzZ",
    "date": "2026-09-11",
    "comment": "encore",
    "playerId": "q1gmRkXPx0WIltpNhcovU0RI1X43",
    "playerFirstName": "arnaud",
    "playerLastName": "goacolou",
    "playerNickName": "nono",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "BE2YNHjhYo1ZO0rmfesU",
    "date": "2026-09-25",
    "comment": "refuse de cadrer",
    "playerId": "imPqpb4QodNbur8A2402Y0ViqtU2",
    "playerFirstName": "nathan",
    "playerLastName": "noumowe",
    "playerNickName": "noumox",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "CCIkoKGKcbsnfjJA2L2N",
    "date": "2026-09-25",
    "comment": "balle gogolisée",
    "playerId": "93lQ1dUdQROHAWxXugCywoP4mFZ2",
    "playerFirstName": "vincent",
    "playerLastName": "garnier",
    "playerNickName": "vincent",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "COgQcT4qMgVsPk68toPT",
    "date": "2026-09-11",
    "comment": "deux mains",
    "playerId": "imPqpb4QodNbur8A2402Y0ViqtU2",
    "playerFirstName": "nathan",
    "playerLastName": "noumowe",
    "playerNickName": "noumox",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "CVetaXTGFwAMoAZecQOg",
    "date": "2026-09-19",
    "comment": "motion 2",
    "playerId": "iWw4sZUo6lZLYlVJhsK3Jsjy0cH2",
    "playerFirstName": "julien",
    "playerLastName": "tessier",
    "playerNickName": "tess",
    "matchDay": true,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 8
  },
  {
    "id": "CtA7DLL06QHsktJdOY2g",
    "date": "2026-09-09",
    "comment": "Vulgarité ",
    "playerId": "rro3OQIjAeZqeZMsJs6ppw15byN2",
    "playerFirstName": "arthur",
    "playerLastName": "barreau",
    "playerNickName": "arthur",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "DrDpf5K4hS1TrmaBMaUJ",
    "date": "2026-09-25",
    "comment": "contre motion",
    "playerId": "RxCeoNlkiQTp3lzwRlqlN8FFAld2",
    "playerFirstName": "pierrick",
    "playerLastName": "royer",
    "playerNickName": "pierrick",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "Dv7k68qgIzocSPcgIio7",
    "date": "2026-09-04",
    "comment": "Pardon coach",
    "playerId": "W6OaWBB73yYfVAZcMwapwKeGN3G3",
    "playerFirstName": "kévin",
    "playerLastName": "merit",
    "playerNickName": "kev",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "E0gQk3fBqQMkImVfsoLh",
    "date": "2026-09-11",
    "comment": "",
    "playerId": "W6OaWBB73yYfVAZcMwapwKeGN3G3",
    "playerFirstName": "kévin",
    "playerLastName": "merit",
    "playerNickName": "kev",
    "matchDay": false,
    "ruleId": "3Avbmn5WDjhkbQvcsNTz",
    "ruleLabel": "Salissure",
    "amount": 2
  },
  {
    "id": "EISMm37xLwErTneJUaZb",
    "date": "2026-09-11",
    "comment": "sale passe",
    "playerId": "imPqpb4QodNbur8A2402Y0ViqtU2",
    "playerFirstName": "nathan",
    "playerLastName": "noumowe",
    "playerNickName": "noumox",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "FBO7us8RgCdACcvPk7DU",
    "date": "2026-09-25",
    "comment": "Motion 2 (j'arrive pas à lire l'écriture de baz)",
    "playerId": "J2I5fRNomfdqvJ0Kybc4Ps4IPSr1",
    "playerFirstName": "thomas",
    "playerLastName": "legagneux",
    "playerNickName": "gagneux",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "FKpN76qnbmcEo8mwvygR",
    "date": "2026-09-23",
    "comment": "",
    "playerId": "imPqpb4QodNbur8A2402Y0ViqtU2",
    "playerFirstName": "nathan",
    "playerLastName": "noumowe",
    "playerNickName": "noumox",
    "matchDay": false,
    "ruleId": "gVvH1uixkHKYgBX3AsMe",
    "ruleLabel": "Retard > 10'",
    "amount": 3
  },
  {
    "id": "FbFecCVIDe7rVUy3x1yo",
    "date": "2026-09-11",
    "comment": "Mime",
    "playerId": "W6OaWBB73yYfVAZcMwapwKeGN3G3",
    "playerFirstName": "kévin",
    "playerLastName": "merit",
    "playerNickName": "kev",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "G3vrufmvmpzKggzPB96B",
    "date": "2026-09-06",
    "comment": "",
    "playerId": "T2u3qJAVmxaEQTtSR53ldAAQWDk2",
    "playerFirstName": "odelin",
    "playerLastName": "baubineau",
    "playerNickName": "o2",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "GKrsSwbcXxphc8IDhXeS",
    "date": "2026-09-11",
    "comment": "Contre",
    "playerId": "r2VQWG7glterTCdxOWGdNfwHewm1",
    "playerFirstName": "basile",
    "playerLastName": "bolcato",
    "playerNickName": "baz",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "GPLNwmsRSjKzg0Gfy0RR",
    "date": "2026-09-25",
    "comment": "passe baballe",
    "playerId": "gF6SAZmnKxe75sYtWuRz1uGBiFp2",
    "playerFirstName": "rayan",
    "playerLastName": "aitouarabi",
    "playerNickName": "rayan",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "Gpl2zJLxmajwfxxxLJkb",
    "date": "2026-09-20",
    "comment": "contre motion",
    "playerId": "XN33ZCiXKsVWi6j34URzz7nlLYq2",
    "playerFirstName": "legault",
    "playerLastName": "anatole",
    "playerNickName": "anat",
    "matchDay": true,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 8
  },
  {
    "id": "HcWM4jXQjVvpgHpmY3VG",
    "date": "2026-09-20",
    "comment": "Donnée par anthonin",
    "playerId": "gF6SAZmnKxe75sYtWuRz1uGBiFp2",
    "playerFirstName": "rayan",
    "playerLastName": "aitouarabi",
    "playerNickName": "rayan",
    "matchDay": true,
    "ruleId": "OT8zI91HTJe9CnJPh5JC",
    "ruleLabel": "Goodberg",
    "amount": 2
  },
  {
    "id": "Hh7ScQqwIL8jGdPnQuDU",
    "date": "2026-09-11",
    "comment": "Action très vilaine Boulif-Gaspard",
    "playerId": "GHGR9vlmWHP1RUpFrykHyoWUao53",
    "playerFirstName": "gaspard",
    "playerLastName": "martin penard",
    "playerNickName": "gasp",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "Hn0omoJftGjMbzLSDleI",
    "date": "2026-09-25",
    "comment": "J'ai des nouvelles de basile !",
    "playerId": "I6WgOBkeJBb6E0n3hnqhzdi9MSh2",
    "playerFirstName": "florent",
    "playerLastName": "boulifard",
    "playerNickName": "boulif",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "HurvOGME1qYZOXP7XLWR",
    "date": "2026-09-02",
    "comment": "",
    "playerId": "I6WgOBkeJBb6E0n3hnqhzdi9MSh2",
    "playerFirstName": "florent",
    "playerLastName": "boulifard",
    "playerNickName": "boulif",
    "matchDay": false,
    "ruleId": "gVvH1uixkHKYgBX3AsMe",
    "ruleLabel": "Retard > 10'",
    "amount": 3
  },
  {
    "id": "IE5ktnxTsGv8F4hXXOGl",
    "date": "2026-09-02",
    "comment": "",
    "playerId": "gF6SAZmnKxe75sYtWuRz1uGBiFp2",
    "playerFirstName": "rayan",
    "playerLastName": "aitouarabi",
    "playerNickName": "rayan",
    "matchDay": false,
    "ruleId": "lVDcNgOuIHfmfljSx9Vd",
    "ruleLabel": "Oubli",
    "amount": 2
  },
  {
    "id": "JPrrjt9EYXMS42uLNYIZ",
    "date": "2026-09-13",
    "comment": "merci Anthony super double parade",
    "playerId": "QrikB2bD7ZNQS6rqlvpTXR1rsAz2",
    "playerFirstName": "antoine",
    "playerLastName": "le pape",
    "playerNickName": "antoine",
    "matchDay": true,
    "ruleId": "OT8zI91HTJe9CnJPh5JC",
    "ruleLabel": "Goodberg",
    "amount": 2
  },
  {
    "id": "JqFonyHZOSdVzSQEwOMg",
    "date": "2026-09-06",
    "comment": "Contre motion",
    "playerId": "r2VQWG7glterTCdxOWGdNfwHewm1",
    "playerFirstName": "basile",
    "playerLastName": "bolcato",
    "playerNickName": "baz",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "JsrDGEf6O4ZcF084AXys",
    "date": "2026-09-25",
    "comment": "",
    "playerId": "I6WgOBkeJBb6E0n3hnqhzdi9MSh2",
    "playerFirstName": "florent",
    "playerLastName": "boulifard",
    "playerNickName": "boulif",
    "matchDay": false,
    "ruleId": "3Avbmn5WDjhkbQvcsNTz",
    "ruleLabel": "Salissure",
    "amount": 2
  },
  {
    "id": "K3tCpfP6VcutwV6YB5zD",
    "date": "2026-09-04",
    "comment": "",
    "playerId": "qISge3VUD7dxpKdgsLJDnD9fMSi2",
    "playerFirstName": "valentin",
    "playerLastName": "gaschard",
    "playerNickName": "valgash",
    "matchDay": false,
    "ruleId": "3Avbmn5WDjhkbQvcsNTz",
    "ruleLabel": "Salissure",
    "amount": 2
  },
  {
    "id": "K6fShTxDJzOzkMJWSEFV",
    "date": "2026-09-04",
    "comment": "",
    "playerId": "RxCeoNlkiQTp3lzwRlqlN8FFAld2",
    "playerFirstName": "pierrick",
    "playerLastName": "royer",
    "playerNickName": "pierrick",
    "matchDay": false,
    "ruleId": "3Avbmn5WDjhkbQvcsNTz",
    "ruleLabel": "Salissure",
    "amount": 2
  },
  {
    "id": "KiJCHxa5ibTIshNJ2VzI",
    "date": "2026-09-11",
    "comment": "Tir dans le dos tout vilain",
    "playerId": "x1a3efMWZyUAnzjlhv73DK1ijxg2",
    "playerFirstName": "romain",
    "playerLastName": "lamirault",
    "playerNickName": "miro",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "Kqe0W4di46qZBkpLPuHl",
    "date": "2026-09-25",
    "comment": "donnée par tess",
    "playerId": "rro3OQIjAeZqeZMsJs6ppw15byN2",
    "playerFirstName": "arthur",
    "playerLastName": "barreau",
    "playerNickName": "arthur",
    "matchDay": true,
    "ruleId": "OT8zI91HTJe9CnJPh5JC",
    "ruleLabel": "Goodberg",
    "amount": 2
  },
  {
    "id": "LHl9TcGTI6jeXVrLHTeg",
    "date": "2026-09-06",
    "comment": "Contre motion",
    "playerId": "imPqpb4QodNbur8A2402Y0ViqtU2",
    "playerFirstName": "nathan",
    "playerLastName": "noumowe",
    "playerNickName": "noumox",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "MfNTSr3UENjDh2E0YVUm",
    "date": "2026-09-11",
    "comment": "débile",
    "playerId": "r2VQWG7glterTCdxOWGdNfwHewm1",
    "playerFirstName": "basile",
    "playerLastName": "bolcato",
    "playerNickName": "baz",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "NGsAoLnALwww6yowzYcU",
    "date": "2026-09-10",
    "comment": "",
    "playerId": "DkxnMTfHHCXxECTwKQJx0UJt1FI3",
    "playerFirstName": "emile",
    "playerLastName": "miot",
    "playerNickName": "emile",
    "matchDay": false,
    "ruleId": "lVDcNgOuIHfmfljSx9Vd",
    "ruleLabel": "Oubli",
    "amount": 2
  },
  {
    "id": "NOlQP6C5Nd25dJreeXpE",
    "date": "2026-09-06",
    "comment": "Motion 1",
    "playerId": "DkxnMTfHHCXxECTwKQJx0UJt1FI3",
    "playerFirstName": "emile",
    "playerLastName": "miot",
    "playerNickName": "emile",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "NVnFhyyIeNVbfNSeHaeN",
    "date": "2026-09-25",
    "comment": "",
    "playerId": "I6WgOBkeJBb6E0n3hnqhzdi9MSh2",
    "playerFirstName": "florent",
    "playerLastName": "boulifard",
    "playerNickName": "boulif",
    "matchDay": false,
    "ruleId": "3Avbmn5WDjhkbQvcsNTz",
    "ruleLabel": "Salissure",
    "amount": 2
  },
  {
    "id": "NirJHElXBW5ypfwhGADm",
    "date": "2026-09-13",
    "comment": "racisme anti roux ",
    "playerId": "J2I5fRNomfdqvJ0Kybc4Ps4IPSr1",
    "playerFirstName": "thomas",
    "playerLastName": "legagneux",
    "playerNickName": "gagneux",
    "matchDay": true,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 8
  },
  {
    "id": "NueArElWCnQV8NknHu9e",
    "date": "2026-09-02",
    "comment": "Deuxième",
    "playerId": "rro3OQIjAeZqeZMsJs6ppw15byN2",
    "playerFirstName": "arthur",
    "playerLastName": "barreau",
    "playerNickName": "arthur",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "OC2iwK7TGU2TqGcpZkXs",
    "date": "2026-09-13",
    "comment": "contre motion",
    "playerId": "n4JsbShjHScgizPyUf0BBLFlgz72",
    "playerFirstName": "yohan",
    "playerLastName": "Nouet",
    "playerNickName": "yo",
    "matchDay": true,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 8
  },
  {
    "id": "OM65DlFhAlJ9Gzauc3IP",
    "date": "2026-09-13",
    "comment": "",
    "playerId": "r2VQWG7glterTCdxOWGdNfwHewm1",
    "playerFirstName": "basile",
    "playerLastName": "bolcato",
    "playerNickName": "baz",
    "matchDay": true,
    "ruleId": "3Avbmn5WDjhkbQvcsNTz",
    "ruleLabel": "Salissure",
    "amount": 4
  },
  {
    "id": "OfSQUe7UCNa2NJSUg7Nh",
    "date": "2026-09-11",
    "comment": "Chab sur le crâne",
    "playerId": "W6OaWBB73yYfVAZcMwapwKeGN3G3",
    "playerFirstName": "kévin",
    "playerLastName": "merit",
    "playerNickName": "kev",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "Ogjuuqw5RPaBflUx36pS",
    "date": "2026-09-25",
    "comment": "balle gogolisée",
    "playerId": "RxCeoNlkiQTp3lzwRlqlN8FFAld2",
    "playerFirstName": "pierrick",
    "playerLastName": "royer",
    "playerNickName": "pierrick",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "OnQQicSi70enVeJ2O6Qf",
    "date": "2026-09-13",
    "comment": "\"Pénalty\"",
    "playerId": "I6WgOBkeJBb6E0n3hnqhzdi9MSh2",
    "playerFirstName": "florent",
    "playerLastName": "boulifard",
    "playerNickName": "boulif",
    "matchDay": true,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 8
  },
  {
    "id": "P0Gf6WxeHO4CQBrRUcF3",
    "date": "2026-09-06",
    "comment": "Déliquant",
    "playerId": "gF6SAZmnKxe75sYtWuRz1uGBiFp2",
    "playerFirstName": "rayan",
    "playerLastName": "aitouarabi",
    "playerNickName": "rayan",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "PFxYjUAhBd88SpZrVSvF",
    "date": "2026-09-13",
    "comment": "contre motion",
    "playerId": "r2VQWG7glterTCdxOWGdNfwHewm1",
    "playerFirstName": "basile",
    "playerLastName": "bolcato",
    "playerNickName": "baz",
    "matchDay": true,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 8
  },
  {
    "id": "PeIpelvkVg6RnQyk70qR",
    "date": "2026-09-12",
    "comment": "Pyramide humaine ",
    "playerId": "TSY4IqLIqoWG6f6UhVOsXvyQmnc2",
    "playerFirstName": "baptiste",
    "playerLastName": "Baubineau",
    "playerNickName": "baptiste",
    "matchDay": true,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 8
  },
  {
    "id": "PkpmWyBUC4yrz9EvEyCk",
    "date": "2026-09-19",
    "comment": "",
    "playerId": "zjvnZVd7YUWGbeVHUj2uqYHLtcf2",
    "playerFirstName": "alexandre",
    "playerLastName": "couloir",
    "playerNickName": "alex",
    "matchDay": true,
    "ruleId": "lVDcNgOuIHfmfljSx9Vd",
    "ruleLabel": "Oubli",
    "amount": 4
  },
  {
    "id": "Q8aQZIEO5zOaLVGoAEVs",
    "date": "2026-09-13",
    "comment": "Viande dans le verre",
    "playerId": "r2VQWG7glterTCdxOWGdNfwHewm1",
    "playerFirstName": "basile",
    "playerLastName": "bolcato",
    "playerNickName": "baz",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "QW7aWwyPLJNc1ulXZLOn",
    "date": "2026-09-13",
    "comment": "C'est où le warehouse ?",
    "playerId": "imPqpb4QodNbur8A2402Y0ViqtU2",
    "playerFirstName": "nathan",
    "playerLastName": "noumowe",
    "playerNickName": "noumox",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "Qm0q3RRVYNg8Pf2gJMnE",
    "date": "2026-09-25",
    "comment": "",
    "playerId": "x7cFO4biRmfuaCzA5z3zEtYCRwb2",
    "playerFirstName": "corentin",
    "playerLastName": "bezin",
    "playerNickName": "coco",
    "matchDay": false,
    "ruleId": "EljtmnPY83UZXucSvkJe",
    "ruleLabel": "Retard < 5'",
    "amount": 2
  },
  {
    "id": "QxAD9QguwEev4bor8MeG",
    "date": "2026-09-13",
    "comment": "l'adversaire me donne le ballon et je ne bouge plus ",
    "playerId": "93lQ1dUdQROHAWxXugCywoP4mFZ2",
    "playerFirstName": "vincent",
    "playerLastName": "garnier",
    "playerNickName": "vincent",
    "matchDay": true,
    "ruleId": "AOgAsPJcNFg0To6yHtve",
    "ruleLabel": "Quéquette",
    "amount": 5
  },
  {
    "id": "RJyhjdrcM7TDrqka9Qtx",
    "date": "2026-09-11",
    "comment": "Rate la balle au foothand",
    "playerId": "q1gmRkXPx0WIltpNhcovU0RI1X43",
    "playerFirstName": "arnaud",
    "playerLastName": "goacolou",
    "playerNickName": "nono",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "SWdykW7wxPQAEbOPXmpy",
    "date": "2026-09-11",
    "comment": "débile ",
    "playerId": "W6OaWBB73yYfVAZcMwapwKeGN3G3",
    "playerFirstName": "kévin",
    "playerLastName": "merit",
    "playerNickName": "kev",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "Sl3QUB9aFY2NDJm3NLBU",
    "date": "2026-09-13",
    "comment": "sale",
    "playerId": "ESESf5Aq3madkW7yD9n2dZ7lBXH3",
    "playerFirstName": "romain",
    "playerLastName": "le potier",
    "playerNickName": "romain",
    "matchDay": true,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 8
  },
  {
    "id": "T0jLToUwgYnyjtX7MJzl",
    "date": "2026-09-02",
    "comment": "",
    "playerId": "0lUs80DSbvVpfRONcTw76OUocMp2",
    "playerFirstName": "brok",
    "playerLastName": "m. brok",
    "playerNickName": "brok",
    "matchDay": false,
    "ruleId": "3Avbmn5WDjhkbQvcsNTz",
    "ruleLabel": "Salissure",
    "amount": 2
  },
  {
    "id": "U3zE5F3O6l1YqGMWjijI",
    "date": "2026-09-09",
    "comment": "",
    "playerId": "r2VQWG7glterTCdxOWGdNfwHewm1",
    "playerFirstName": "basile",
    "playerLastName": "bolcato",
    "playerNickName": "baz",
    "matchDay": false,
    "ruleId": "3Avbmn5WDjhkbQvcsNTz",
    "ruleLabel": "Salissure",
    "amount": 2
  },
  {
    "id": "UEWmnuUWp3NcnqCv5yAe",
    "date": "2026-09-19",
    "comment": "",
    "playerId": "imPqpb4QodNbur8A2402Y0ViqtU2",
    "playerFirstName": "nathan",
    "playerLastName": "noumowe",
    "playerNickName": "noumox",
    "matchDay": true,
    "ruleId": "gVvH1uixkHKYgBX3AsMe",
    "ruleLabel": "Retard > 10'",
    "amount": 6
  },
  {
    "id": "UGmZigH8K5PmMSezMXBU",
    "date": "2026-09-13",
    "comment": "contre motion",
    "playerId": "W6OaWBB73yYfVAZcMwapwKeGN3G3",
    "playerFirstName": "kévin",
    "playerLastName": "merit",
    "playerNickName": "kev",
    "matchDay": true,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 8
  },
  {
    "id": "UooRYzs7jjKF4mAFdZUK",
    "date": "2026-09-06",
    "comment": "Boulard ",
    "playerId": "RxCeoNlkiQTp3lzwRlqlN8FFAld2",
    "playerFirstName": "pierrick",
    "playerLastName": "royer",
    "playerNickName": "pierrick",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "V890J6KFuxyWDeeGhnLD",
    "date": "2026-09-02",
    "comment": "",
    "playerId": "T2u3qJAVmxaEQTtSR53ldAAQWDk2",
    "playerFirstName": "odelin",
    "playerLastName": "baubineau",
    "playerNickName": "o2",
    "matchDay": false,
    "ruleId": "EljtmnPY83UZXucSvkJe",
    "ruleLabel": "Retard < 5'",
    "amount": 2
  },
  {
    "id": "VOVjW1tM5EqDvXOJSiVf",
    "date": "2026-09-06",
    "comment": "Poteau",
    "playerId": "r2VQWG7glterTCdxOWGdNfwHewm1",
    "playerFirstName": "basile",
    "playerLastName": "bolcato",
    "playerNickName": "baz",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "W2LSOSJURFGTDyzSR5ZX",
    "date": "2026-09-04",
    "comment": "Klaxon de temps mort",
    "playerId": "gF6SAZmnKxe75sYtWuRz1uGBiFp2",
    "playerFirstName": "rayan",
    "playerLastName": "aitouarabi",
    "playerNickName": "rayan",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "WedLOtGauv0Ho6Yzjkl6",
    "date": "2026-09-02",
    "comment": "",
    "playerId": "r2VQWG7glterTCdxOWGdNfwHewm1",
    "playerFirstName": "basile",
    "playerLastName": "bolcato",
    "playerNickName": "baz",
    "matchDay": false,
    "ruleId": "gVvH1uixkHKYgBX3AsMe",
    "ruleLabel": "Retard > 10'",
    "amount": 3
  },
  {
    "id": "XAo3H88gurRcSX2GsXB2",
    "date": "2026-09-09",
    "comment": "",
    "playerId": "RxCeoNlkiQTp3lzwRlqlN8FFAld2",
    "playerFirstName": "pierrick",
    "playerLastName": "royer",
    "playerNickName": "pierrick",
    "matchDay": false,
    "ruleId": "pSVnwSZUEaWlk7VCDmMc",
    "ruleLabel": "Retard < 15'",
    "amount": 5
  },
  {
    "id": "XVCf9O0IArTgPhkMPZf0",
    "date": "2026-09-04",
    "comment": "Passe pas le milieu de terrain",
    "playerId": "0lUs80DSbvVpfRONcTw76OUocMp2",
    "playerFirstName": "brok",
    "playerLastName": "m. brok",
    "playerNickName": "brok",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "XVO4kG4XAy7cxY0lH8f4",
    "date": "2026-09-20",
    "comment": "",
    "playerId": "XN33ZCiXKsVWi6j34URzz7nlLYq2",
    "playerFirstName": "legault",
    "playerLastName": "anatole",
    "playerNickName": "anat",
    "matchDay": true,
    "ruleId": "AOgAsPJcNFg0To6yHtve",
    "ruleLabel": "Quéquette",
    "amount": 5
  },
  {
    "id": "Y5hMyRtigZqXhPzLoF8t",
    "date": "2026-09-13",
    "comment": "contre motion",
    "playerId": "imPqpb4QodNbur8A2402Y0ViqtU2",
    "playerFirstName": "nathan",
    "playerLastName": "noumowe",
    "playerNickName": "noumox",
    "matchDay": true,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 8
  },
  {
    "id": "YJKaHwCgQKJzoKNolz9S",
    "date": "2026-09-04",
    "comment": "",
    "playerId": "HF7TqiV8ajZ5dF3vTqqSdmZu4ht2",
    "playerFirstName": "estébane",
    "playerLastName": "gouhey",
    "playerNickName": "st",
    "matchDay": false,
    "ruleId": "EljtmnPY83UZXucSvkJe",
    "ruleLabel": "Retard < 5'",
    "amount": 2
  },
  {
    "id": "Yl6jDohLrVmeIzNZOf1J",
    "date": "2026-09-13",
    "comment": "\"protocole \"",
    "playerId": "RxCeoNlkiQTp3lzwRlqlN8FFAld2",
    "playerFirstName": "pierrick",
    "playerLastName": "royer",
    "playerNickName": "pierrick",
    "matchDay": true,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 8
  },
  {
    "id": "Ymzvnp6urgQmForPB6us",
    "date": "2026-09-05",
    "comment": "Palifico",
    "playerId": "imPqpb4QodNbur8A2402Y0ViqtU2",
    "playerFirstName": "nathan",
    "playerLastName": "noumowe",
    "playerNickName": "noumox",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "YqXtoMnz4n87e9elwAmv",
    "date": "2026-09-19",
    "comment": "Motion 1",
    "playerId": "fkHinu5oagRwOBLXbujY6c0BJUn2",
    "playerFirstName": "nicolas",
    "playerLastName": "daniaud",
    "playerNickName": "nico",
    "matchDay": true,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 8
  },
  {
    "id": "ZGhAEhtrOwvGrYmgph0R",
    "date": "2026-09-20",
    "comment": "",
    "playerId": "x1a3efMWZyUAnzjlhv73DK1ijxg2",
    "playerFirstName": "romain",
    "playerLastName": "lamirault",
    "playerNickName": "miro",
    "matchDay": true,
    "ruleId": "7BspPAHRat12qQruZQte",
    "ruleLabel": "Contestation",
    "amount": 10
  },
  {
    "id": "ZpoxIJJE75nvbBQTud9G",
    "date": "2026-09-25",
    "comment": "Donnée par tess",
    "playerId": "fkHinu5oagRwOBLXbujY6c0BJUn2",
    "playerFirstName": "nicolas",
    "playerLastName": "daniaud",
    "playerNickName": "nico",
    "matchDay": false,
    "ruleId": "nDe1tvnRY3O5a4qlb3CQ",
    "ruleLabel": "Homme du match",
    "amount": 2
  },
  {
    "id": "ZzNiYMjIxAZnH9UOHc54",
    "date": "2026-09-11",
    "comment": "Ça s'écrit \"Schwenker\"",
    "playerId": "rro3OQIjAeZqeZMsJs6ppw15byN2",
    "playerFirstName": "arthur",
    "playerLastName": "barreau",
    "playerNickName": "arthur",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "aEHIkLoUGBHWBf76xniK",
    "date": "2026-09-02",
    "comment": "petit souci de départ sur le fractionné",
    "playerId": "rro3OQIjAeZqeZMsJs6ppw15byN2",
    "playerFirstName": "arthur",
    "playerLastName": "barreau",
    "playerNickName": "arthur",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "bfjW5H6Cr1aqc7jlEgwd",
    "date": "2026-09-13",
    "comment": "passe en touche",
    "playerId": "r2VQWG7glterTCdxOWGdNfwHewm1",
    "playerFirstName": "basile",
    "playerLastName": "bolcato",
    "playerNickName": "baz",
    "matchDay": true,
    "ruleId": "AOgAsPJcNFg0To6yHtve",
    "ruleLabel": "Quéquette",
    "amount": 5
  },
  {
    "id": "c8lnBgIz2ObGfVU4n1YB",
    "date": "2026-09-02",
    "comment": "casquette déposée au bureau",
    "playerId": "gF6SAZmnKxe75sYtWuRz1uGBiFp2",
    "playerFirstName": "rayan",
    "playerLastName": "aitouarabi",
    "playerNickName": "rayan",
    "matchDay": false,
    "ruleId": "lVDcNgOuIHfmfljSx9Vd",
    "ruleLabel": "Oubli",
    "amount": 2
  },
  {
    "id": "cYhqN6anh5cgp3OUo7Lc",
    "date": "2026-09-06",
    "comment": "Joanna",
    "playerId": "r2VQWG7glterTCdxOWGdNfwHewm1",
    "playerFirstName": "basile",
    "playerLastName": "bolcato",
    "playerNickName": "baz",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "cii2pUitIGMQ9gnMzVXh",
    "date": "2026-09-23",
    "comment": "Chaussures de la petite soeur",
    "playerId": "ESESf5Aq3madkW7yD9n2dZ7lBXH3",
    "playerFirstName": "romain",
    "playerLastName": "le potier",
    "playerNickName": "romain",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "d3bwDtktOb5RdLhb0Hlh",
    "date": "2026-09-06",
    "comment": "Mettez moi une motion, je m'en fous",
    "playerId": "gF6SAZmnKxe75sYtWuRz1uGBiFp2",
    "playerFirstName": "rayan",
    "playerLastName": "aitouarabi",
    "playerNickName": "rayan",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "dAIGdijKtR5NFZSe3V9l",
    "date": "2026-09-13",
    "comment": "c'est qui chloé ?",
    "playerId": "rro3OQIjAeZqeZMsJs6ppw15byN2",
    "playerFirstName": "arthur",
    "playerLastName": "barreau",
    "playerNickName": "arthur",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "dHwgtJogICNn3YvsmBp0",
    "date": "2026-09-06",
    "comment": "Que double parade",
    "playerId": "RxCeoNlkiQTp3lzwRlqlN8FFAld2",
    "playerFirstName": "pierrick",
    "playerLastName": "royer",
    "playerNickName": "pierrick",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "dXsPYxgFIM94RCQ0Jb9R",
    "date": "2026-09-11",
    "comment": "Prout très cracra",
    "playerId": "I6WgOBkeJBb6E0n3hnqhzdi9MSh2",
    "playerFirstName": "florent",
    "playerLastName": "boulifard",
    "playerNickName": "boulif",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "fbwHSrKfVBidsj4zbd1H",
    "date": "2026-09-19",
    "comment": "Motion 1",
    "playerId": "iWw4sZUo6lZLYlVJhsK3Jsjy0cH2",
    "playerFirstName": "julien",
    "playerLastName": "tessier",
    "playerNickName": "tess",
    "matchDay": true,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 8
  },
  {
    "id": "fy1wYuHmtKdMVgJYHjZG",
    "date": "2026-09-11",
    "comment": "débilos",
    "playerId": "r2VQWG7glterTCdxOWGdNfwHewm1",
    "playerFirstName": "basile",
    "playerLastName": "bolcato",
    "playerNickName": "baz",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "gXjTAY13y2jgUiZf0uTX",
    "date": "2026-09-25",
    "comment": "passe baballe",
    "playerId": "DkxnMTfHHCXxECTwKQJx0UJt1FI3",
    "playerFirstName": "emile",
    "playerLastName": "miot",
    "playerNickName": "emile",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "gXvIIknGWTiH5liOYCbd",
    "date": "2026-09-02",
    "comment": "",
    "playerId": "imPqpb4QodNbur8A2402Y0ViqtU2",
    "playerFirstName": "nathan",
    "playerLastName": "noumowe",
    "playerNickName": "noumox",
    "matchDay": false,
    "ruleId": "3Avbmn5WDjhkbQvcsNTz",
    "ruleLabel": "Salissure",
    "amount": 2
  },
  {
    "id": "gZ8cg9jZhrgVK4S9BFyj",
    "date": "2026-09-06",
    "comment": "4 contre 1 massacré",
    "playerId": "GHGR9vlmWHP1RUpFrykHyoWUao53",
    "playerFirstName": "gaspard",
    "playerLastName": "martin penard",
    "playerNickName": "gasp",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "gmXxCE1OJBP4TC4UFiLy",
    "date": "2026-09-25",
    "comment": "",
    "playerId": "HF7TqiV8ajZ5dF3vTqqSdmZu4ht2",
    "playerFirstName": "estébane",
    "playerLastName": "gouhey",
    "playerNickName": "st",
    "matchDay": false,
    "ruleId": "EljtmnPY83UZXucSvkJe",
    "ruleLabel": "Retard < 5'",
    "amount": 2
  },
  {
    "id": "hCK1iWSQB3HeeZJxd62R",
    "date": "2026-09-25",
    "comment": "",
    "playerId": "CiQwIFhyoUVejJ9wukMvNPtgfLg2",
    "playerFirstName": "mathieu",
    "playerLastName": "garnier",
    "playerNickName": "math",
    "matchDay": false,
    "ruleId": "EljtmnPY83UZXucSvkJe",
    "ruleLabel": "Retard < 5'",
    "amount": 2
  },
  {
    "id": "hT7bVxvaPndkSQHNjYCR",
    "date": "2026-09-25",
    "comment": "",
    "playerId": "iWw4sZUo6lZLYlVJhsK3Jsjy0cH2",
    "playerFirstName": "julien",
    "playerLastName": "tessier",
    "playerNickName": "tess",
    "matchDay": true,
    "ruleId": "AOgAsPJcNFg0To6yHtve",
    "ruleLabel": "Quéquette",
    "amount": 5
  },
  {
    "id": "hhuCRZg0is61906FBL5z",
    "date": "2026-09-25",
    "comment": "",
    "playerId": "W6OaWBB73yYfVAZcMwapwKeGN3G3",
    "playerFirstName": "kévin",
    "playerLastName": "merit",
    "playerNickName": "kev",
    "matchDay": false,
    "ruleId": "3Avbmn5WDjhkbQvcsNTz",
    "ruleLabel": "Salissure",
    "amount": 2
  },
  {
    "id": "hql6PsjG4WSqikdka92Y",
    "date": "2026-09-23",
    "comment": "Broc grosse boule de merde",
    "playerId": "imPqpb4QodNbur8A2402Y0ViqtU2",
    "playerFirstName": "nathan",
    "playerLastName": "noumowe",
    "playerNickName": "noumox",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "igHohXhgpckKJpKMNc2i",
    "date": "2026-09-20",
    "comment": "",
    "playerId": "imPqpb4QodNbur8A2402Y0ViqtU2",
    "playerFirstName": "nathan",
    "playerLastName": "noumowe",
    "playerNickName": "noumox",
    "matchDay": true,
    "ruleId": "3Avbmn5WDjhkbQvcsNTz",
    "ruleLabel": "Salissure",
    "amount": 4
  },
  {
    "id": "ijbnDlUJbKnAwkMmyJYL",
    "date": "2026-09-20",
    "comment": "Perrier Biggy",
    "playerId": "imPqpb4QodNbur8A2402Y0ViqtU2",
    "playerFirstName": "nathan",
    "playerLastName": "noumowe",
    "playerNickName": "noumox",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "ioZvHsrK2S9P21fuKROu",
    "date": "2026-09-19",
    "comment": "Erreur de table",
    "playerId": "QrikB2bD7ZNQS6rqlvpTXR1rsAz2",
    "playerFirstName": "antoine",
    "playerLastName": "le pape",
    "playerNickName": "antoine",
    "matchDay": true,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 8
  },
  {
    "id": "jWxfr6wn6JVdjAJQJubO",
    "date": "2026-09-02",
    "comment": "",
    "playerId": "imPqpb4QodNbur8A2402Y0ViqtU2",
    "playerFirstName": "nathan",
    "playerLastName": "noumowe",
    "playerNickName": "noumox",
    "matchDay": false,
    "ruleId": "EljtmnPY83UZXucSvkJe",
    "ruleLabel": "Retard < 5'",
    "amount": 2
  },
  {
    "id": "jtC3XMK4k17k3yP0XF37",
    "date": "2026-09-02",
    "comment": "",
    "playerId": "jnHag6vVpYZGlRMEPek7a6sA1GD2",
    "playerFirstName": "anthony",
    "playerLastName": "haté",
    "playerNickName": "grantho",
    "matchDay": false,
    "ruleId": "lVDcNgOuIHfmfljSx9Vd",
    "ruleLabel": "Oubli",
    "amount": 2
  },
  {
    "id": "k8A6XvfJp79qI9tPgKuK",
    "date": "2026-09-02",
    "comment": "petit souci de départ sur le fractionné",
    "playerId": "n4JsbShjHScgizPyUf0BBLFlgz72",
    "playerFirstName": "yohan",
    "playerLastName": "Nouet",
    "playerNickName": "yo",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "kkMxhu5zsytza4eLRtcK",
    "date": "2026-09-13",
    "comment": "",
    "playerId": "RxCeoNlkiQTp3lzwRlqlN8FFAld2",
    "playerFirstName": "pierrick",
    "playerLastName": "royer",
    "playerNickName": "pierrick",
    "matchDay": true,
    "ruleId": "OT8zI91HTJe9CnJPh5JC",
    "ruleLabel": "Goodberg",
    "amount": 2
  },
  {
    "id": "l6osJ66Yo5IBGtvugu3x",
    "date": "2026-09-09",
    "comment": "contre motion",
    "playerId": "HF7TqiV8ajZ5dF3vTqqSdmZu4ht2",
    "playerFirstName": "estébane",
    "playerLastName": "gouhey",
    "playerNickName": "st",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "lWfpO1qna300OGE13gUU",
    "date": "2026-09-11",
    "comment": "deux mains",
    "playerId": "qISge3VUD7dxpKdgsLJDnD9fMSi2",
    "playerFirstName": "valentin",
    "playerLastName": "gaschard",
    "playerNickName": "valgash",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "mdE3yUJXKuiaOxMO0hlT",
    "date": "2026-09-11",
    "comment": "peur",
    "playerId": "imPqpb4QodNbur8A2402Y0ViqtU2",
    "playerFirstName": "nathan",
    "playerLastName": "noumowe",
    "playerNickName": "noumox",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "n6VyM0OHOFzlfO1uEqhq",
    "date": "2026-09-11",
    "comment": "Action très vilaine Boulif-Gaspard",
    "playerId": "I6WgOBkeJBb6E0n3hnqhzdi9MSh2",
    "playerFirstName": "florent",
    "playerLastName": "boulifard",
    "playerNickName": "boulif",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "ngB7e7BEaD1OWBkxGKRL",
    "date": "2026-09-09",
    "comment": "Commence l'exercice trop tôt",
    "playerId": "84aYjwJdyZcGQ46g5ft8LJlgG0o1",
    "playerFirstName": "mathis",
    "playerLastName": "foret",
    "playerNickName": "rouqumoutte",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "nnzsbSovpLk3KMt2fzQA",
    "date": "2026-09-06",
    "comment": "Motion nul",
    "playerId": "RxCeoNlkiQTp3lzwRlqlN8FFAld2",
    "playerFirstName": "pierrick",
    "playerLastName": "royer",
    "playerNickName": "pierrick",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "noZqAigxHwn80woNnYyB",
    "date": "2026-09-11",
    "comment": "débilos",
    "playerId": "imPqpb4QodNbur8A2402Y0ViqtU2",
    "playerFirstName": "nathan",
    "playerLastName": "noumowe",
    "playerNickName": "noumox",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "nwT3zz1PTOS9MNp2iShg",
    "date": "2026-09-19",
    "comment": "",
    "playerId": "r2VQWG7glterTCdxOWGdNfwHewm1",
    "playerFirstName": "basile",
    "playerLastName": "bolcato",
    "playerNickName": "baz",
    "matchDay": true,
    "ruleId": "gVvH1uixkHKYgBX3AsMe",
    "ruleLabel": "Retard > 10'",
    "amount": 6
  },
  {
    "id": "ouqGjytNHmtGjDKDhx1r",
    "date": "2026-09-19",
    "comment": "motion 2",
    "playerId": "imPqpb4QodNbur8A2402Y0ViqtU2",
    "playerFirstName": "nathan",
    "playerLastName": "noumowe",
    "playerNickName": "noumox",
    "matchDay": true,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 8
  },
  {
    "id": "poPYMiRswa3gAL4lUdfn",
    "date": "2026-09-13",
    "comment": "",
    "playerId": "x1a3efMWZyUAnzjlhv73DK1ijxg2",
    "playerFirstName": "romain",
    "playerLastName": "lamirault",
    "playerNickName": "miro",
    "matchDay": true,
    "ruleId": "3Avbmn5WDjhkbQvcsNTz",
    "ruleLabel": "Salissure",
    "amount": 4
  },
  {
    "id": "prfCWUlEInUQkqJ8H4lX",
    "date": "2026-09-02",
    "comment": "Bafouille",
    "playerId": "RxCeoNlkiQTp3lzwRlqlN8FFAld2",
    "playerFirstName": "pierrick",
    "playerLastName": "royer",
    "playerNickName": "pierrick",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "s7wCdRDn8uFAQoreLpiR",
    "date": "2026-09-25",
    "comment": "pas dans le groupe sm2",
    "playerId": "qISge3VUD7dxpKdgsLJDnD9fMSi2",
    "playerFirstName": "valentin",
    "playerLastName": "gaschard",
    "playerNickName": "valgash",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "sfYnYJG0La8C3UU6h0QU",
    "date": "2026-09-23",
    "comment": "",
    "playerId": "GHGR9vlmWHP1RUpFrykHyoWUao53",
    "playerFirstName": "gaspard",
    "playerLastName": "martin penard",
    "playerNickName": "gasp",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "t7Jt5bHa9OQf06IBTKQY",
    "date": "2026-09-02",
    "comment": "petit souci de départ sur le fractionné",
    "playerId": "0lUs80DSbvVpfRONcTw76OUocMp2",
    "playerFirstName": "brok",
    "playerLastName": "m. brok",
    "playerNickName": "brok",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "t7PoLY5hOJEmWqBs32Q0",
    "date": "2026-09-12",
    "comment": "",
    "playerId": "iWw4sZUo6lZLYlVJhsK3Jsjy0cH2",
    "playerFirstName": "julien",
    "playerLastName": "tessier",
    "playerNickName": "tess",
    "matchDay": true,
    "ruleId": "EljtmnPY83UZXucSvkJe",
    "ruleLabel": "Retard < 5'",
    "amount": 4
  },
  {
    "id": "tenBUQS0reFvL5lzu10z",
    "date": "2026-09-11",
    "comment": "Double Schwenker",
    "playerId": "r2VQWG7glterTCdxOWGdNfwHewm1",
    "playerFirstName": "basile",
    "playerLastName": "bolcato",
    "playerNickName": "baz",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "u4Fw71XwrsqXHr1XhMUo",
    "date": "2026-09-09",
    "comment": "\"Et alors ?\"",
    "playerId": "W6OaWBB73yYfVAZcMwapwKeGN3G3",
    "playerFirstName": "kévin",
    "playerLastName": "merit",
    "playerNickName": "kev",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "um2UxmLN1eUtv3MgZH3V",
    "date": "2026-09-01",
    "comment": "",
    "playerId": "ESESf5Aq3madkW7yD9n2dZ7lBXH3",
    "playerFirstName": "romain",
    "playerLastName": "le potier",
    "playerNickName": "romain",
    "matchDay": false,
    "ruleId": "EljtmnPY83UZXucSvkJe",
    "ruleLabel": "Retard < 5'",
    "amount": 2
  },
  {
    "id": "uniRplojSo7uxsQAeWFQ",
    "date": "2026-09-25",
    "comment": "Part trop tôt en fractionné",
    "playerId": "jnHag6vVpYZGlRMEPek7a6sA1GD2",
    "playerFirstName": "anthony",
    "playerLastName": "haté",
    "playerNickName": "grantho",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "usTcrL6Tgn17VZzZMSy4",
    "date": "2026-09-02",
    "comment": "",
    "playerId": "r2VQWG7glterTCdxOWGdNfwHewm1",
    "playerFirstName": "basile",
    "playerLastName": "bolcato",
    "playerNickName": "baz",
    "matchDay": false,
    "ruleId": "lVDcNgOuIHfmfljSx9Vd",
    "ruleLabel": "Oubli",
    "amount": 2
  },
  {
    "id": "vkKnXOMWMfHhq4EcYM6T",
    "date": "2026-09-13",
    "comment": "",
    "playerId": "ESESf5Aq3madkW7yD9n2dZ7lBXH3",
    "playerFirstName": "romain",
    "playerLastName": "le potier",
    "playerNickName": "romain",
    "matchDay": true,
    "ruleId": "lVDcNgOuIHfmfljSx9Vd",
    "ruleLabel": "Oubli",
    "amount": 4
  },
  {
    "id": "w7yJUi4wmdVSJSRx7rli",
    "date": "2026-09-13",
    "comment": "",
    "playerId": "x1a3efMWZyUAnzjlhv73DK1ijxg2",
    "playerFirstName": "romain",
    "playerLastName": "lamirault",
    "playerNickName": "miro",
    "matchDay": false,
    "ruleId": "nDe1tvnRY3O5a4qlb3CQ",
    "ruleLabel": "Homme du match",
    "amount": 2
  },
  {
    "id": "wTHhTbnYmduluuY871Ey",
    "date": "2026-09-19",
    "comment": "Motion 1",
    "playerId": "imPqpb4QodNbur8A2402Y0ViqtU2",
    "playerFirstName": "nathan",
    "playerLastName": "noumowe",
    "playerNickName": "noumox",
    "matchDay": true,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 8
  },
  {
    "id": "wiai1lJPZzyV9Yh9yOoU",
    "date": "2026-09-20",
    "comment": "",
    "playerId": "RxCeoNlkiQTp3lzwRlqlN8FFAld2",
    "playerFirstName": "pierrick",
    "playerLastName": "royer",
    "playerNickName": "pierrick",
    "matchDay": true,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 8
  },
  {
    "id": "x0se1VcOS4kFm3C7Prhh",
    "date": "2026-09-12",
    "comment": "Pyramide humaine ",
    "playerId": "J2I5fRNomfdqvJ0Kybc4Ps4IPSr1",
    "playerFirstName": "thomas",
    "playerLastName": "legagneux",
    "playerNickName": "gagneux",
    "matchDay": true,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 8
  },
  {
    "id": "xG3Kkid2j5mwJfk9U7Yr",
    "date": "2026-09-06",
    "comment": "Se roule par terre",
    "playerId": "DkxnMTfHHCXxECTwKQJx0UJt1FI3",
    "playerFirstName": "emile",
    "playerLastName": "miot",
    "playerNickName": "emile",
    "matchDay": false,
    "ruleId": "",
    "ruleLabel": "",
    "amount": null
  },
  {
    "id": "xSbqaTZMr9LuTiDvdIDP",
    "date": "2026-09-04",
    "comment": "",
    "playerId": "iWw4sZUo6lZLYlVJhsK3Jsjy0cH2",
    "playerFirstName": "julien",
    "playerLastName": "tessier",
    "playerNickName": "tess",
    "matchDay": false,
    "ruleId": "gVvH1uixkHKYgBX3AsMe",
    "ruleLabel": "Retard > 10'",
    "amount": 3
  },
  {
    "id": "yBxZD188u7KIJhOBSW1Z",
    "date": "2026-09-25",
    "comment": "Allume le gardien à l'échauffement",
    "playerId": "J2I5fRNomfdqvJ0Kybc4Ps4IPSr1",
    "playerFirstName": "thomas",
    "playerLastName": "legagneux",
    "playerNickName": "gagneux",
    "matchDay": false,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 4
  },
  {
    "id": "yBym6H83rmZmPHNVvktw",
    "date": "2026-09-13",
    "comment": "prépa intégrée",
    "playerId": "x1a3efMWZyUAnzjlhv73DK1ijxg2",
    "playerFirstName": "romain",
    "playerLastName": "lamirault",
    "playerNickName": "miro",
    "matchDay": true,
    "ruleId": "fpK8HKDF05ZlrSp4NrlK",
    "ruleLabel": "Motion",
    "amount": 8
  },
  {
    "id": "yEW7sK1GiU4Y9o1Hh5j7",
    "date": "2026-09-23",
    "comment": "",
    "playerId": "CiQwIFhyoUVejJ9wukMvNPtgfLg2",
    "playerFirstName": "mathieu",
    "playerLastName": "garnier",
    "playerNickName": "math",
    "matchDay": false,
    "ruleId": "EljtmnPY83UZXucSvkJe",
    "ruleLabel": "Retard < 5'",
    "amount": 2
  },
  {
    "id": "ytQEbLCNmEfC2G9M10gc",
    "date": "2026-09-11",
    "comment": "",
    "playerId": "0lUs80DSbvVpfRONcTw76OUocMp2",
    "playerFirstName": "brok",
    "playerLastName": "m. brok",
    "playerNickName": "brok",
    "matchDay": false,
    "ruleId": "lVDcNgOuIHfmfljSx9Vd",
    "ruleLabel": "Oubli",
    "amount": 2
  },
  {
    "id": "zhvazAiFKbOJtLZxIw8O",
    "date": "2026-09-22",
    "comment": "",
    "playerId": "XN33ZCiXKsVWi6j34URzz7nlLYq2",
    "playerFirstName": "legault",
    "playerLastName": "anatole",
    "playerNickName": "anat",
    "matchDay": false,
    "ruleId": "lVDcNgOuIHfmfljSx9Vd",
    "ruleLabel": "Oubli",
    "amount": 2
  }
];

async function importFines() {
  const batch = db.batch();

  for (const fine of fines) {
    const fineRef = db
      .collection("seasons")
      .doc("2026")
      .collection("fines")
      .doc(fine.id);

    batch.set(fineRef, {
      uid: fine.id,
      playerId: fine.playerId,
      playerFirstName: fine.playerFirstName,
      playerLastName: fine.playerLastName,
      playerNickName: fine.playerNickName,
      comment: fine.comment,
      date : fine.date,
      matchDay: fine.matchDay,
      // photo: fine.photo,
      amount: fine.amount,
      ruleId: fine.ruleId,
      ruleLabel: fine.ruleLabel
    });
  }

  await batch.commit();

  console.log(`✅ ${fines.length} amendes importées dans seasons/2026/fines`);
}

importFines()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("❌ Erreur :", error);
    process.exit(1);
  });